/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SLEECUiModule extends AbstractSLEECUiModule {
  public SLEECUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
