/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends Type
{
} // Boolean
