/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends Definition
{
} // Event
