/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MBool Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getMBoolExpr()
 * @model
 * @generated
 */
public interface MBoolExpr extends EObject
{
} // MBoolExpr
