/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getNot()
 * @model
 * @generated
 */
public interface Not extends MBoolExpr
{
} // Not
