/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rel Comp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.RelComp#getLeft <em>Left</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.RelComp#getOp <em>Op</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.RelComp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRelComp()
 * @model
 * @generated
 */
public interface RelComp extends MBoolExpr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(MBoolExpr)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRelComp_Left()
   * @model containment="true"
   * @generated
   */
  MBoolExpr getLeft();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.RelComp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(MBoolExpr value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link circus.robocalc.sleec.sLEEC.RelOp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see circus.robocalc.sleec.sLEEC.RelOp
   * @see #setOp(RelOp)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRelComp_Op()
   * @model
   * @generated
   */
  RelOp getOp();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.RelComp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see circus.robocalc.sleec.sLEEC.RelOp
   * @see #getOp()
   * @generated
   */
  void setOp(RelOp value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(MBoolExpr)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRelComp_Right()
   * @model containment="true"
   * @generated
   */
  MBoolExpr getRight();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.RelComp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(MBoolExpr value);

} // RelComp
