/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Rule#getName <em>Name</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Rule#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Rule#getResponse <em>Response</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Rule#getDefeaters <em>Defeaters</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference.
   * @see #setTrigger(Trigger)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRule_Trigger()
   * @model containment="true"
   * @generated
   */
  Trigger getTrigger();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Rule#getTrigger <em>Trigger</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' containment reference.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(Trigger value);

  /**
   * Returns the value of the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' containment reference.
   * @see #setResponse(Response)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRule_Response()
   * @model containment="true"
   * @generated
   */
  Response getResponse();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Rule#getResponse <em>Response</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response</em>' containment reference.
   * @see #getResponse()
   * @generated
   */
  void setResponse(Response value);

  /**
   * Returns the value of the '<em><b>Defeaters</b></em>' containment reference list.
   * The list contents are of type {@link circus.robocalc.sleec.sLEEC.Defeater}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defeaters</em>' containment reference list.
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getRule_Defeaters()
   * @model containment="true"
   * @generated
   */
  EList<Defeater> getDefeaters();

} // Rule
