/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Scale#getScaleParams <em>Scale Params</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getScale()
 * @model
 * @generated
 */
public interface Scale extends Type
{
  /**
   * Returns the value of the '<em><b>Scale Params</b></em>' containment reference list.
   * The list contents are of type {@link circus.robocalc.sleec.sLEEC.ScaleParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale Params</em>' containment reference list.
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getScale_ScaleParams()
   * @model containment="true"
   * @generated
   */
  EList<ScaleParam> getScaleParams();

} // Scale
