/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Specification#getDefBlock <em>Def Block</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Specification#getRuleBlock <em>Rule Block</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getSpecification()
 * @model
 * @generated
 */
public interface Specification extends EObject
{
  /**
   * Returns the value of the '<em><b>Def Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Block</em>' containment reference.
   * @see #setDefBlock(Defblock)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getSpecification_DefBlock()
   * @model containment="true"
   * @generated
   */
  Defblock getDefBlock();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Specification#getDefBlock <em>Def Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Block</em>' containment reference.
   * @see #getDefBlock()
   * @generated
   */
  void setDefBlock(Defblock value);

  /**
   * Returns the value of the '<em><b>Rule Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Block</em>' containment reference.
   * @see #setRuleBlock(RuleBlock)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getSpecification_RuleBlock()
   * @model containment="true"
   * @generated
   */
  RuleBlock getRuleBlock();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Specification#getRuleBlock <em>Rule Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule Block</em>' containment reference.
   * @see #getRuleBlock()
   * @generated
   */
  void setRuleBlock(RuleBlock value);

} // Specification
