/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Value#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Constant)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue_Value()
   * @model
   * @generated
   */
  Constant getValue();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Value#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Constant value);

} // Value
