/**
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.sLEEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Value#getInt <em>Int</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Value#getFloat <em>Float</em>}</li>
 *   <li>{@link circus.robocalc.sleec.sLEEC.Value#getConstant <em>Constant</em>}</li>
 * </ul>
 *
 * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Value#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

  /**
   * Returns the value of the '<em><b>Float</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float</em>' attribute.
   * @see #setFloat(float)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue_Float()
   * @model
   * @generated
   */
  float getFloat();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Value#getFloat <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float</em>' attribute.
   * @see #getFloat()
   * @generated
   */
  void setFloat(float value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' reference.
   * @see #setConstant(Constant)
   * @see circus.robocalc.sleec.sLEEC.SLEECPackage#getValue_Constant()
   * @model
   * @generated
   */
  Constant getConstant();

  /**
   * Sets the value of the '{@link circus.robocalc.sleec.sLEEC.Value#getConstant <em>Constant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' reference.
   * @see #getConstant()
   * @generated
   */
  void setConstant(Constant value);

} // Value
