/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SLEECStandaloneSetup extends SLEECStandaloneSetupGenerated {

	public static void doSetup() {
		new SLEECStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
