/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SLEECUiModule extends AbstractSLEECUiModule {

	public SLEECUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
