/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.ui.tests;

import circus.robocalc.sleec.ui.internal.SleecActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SLEECUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SleecActivator.getInstance().getInjector("circus.robocalc.sleec.SLEEC");
	}

}
