/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SLEECAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("circus/robocalc/sleec/parser/antlr/internal/InternalSLEEC.tokens");
	}
}
